### PR TITLE
fix unsupported token issue in url

### LINKED ISSUE #101: [BUG]  Handle unsupported token in URL input for swap fields
**Describe the bug**

When setting the token in the URL to USDT, which isn't supported on the Base network, the application tries to fetch the balance for USDT, resulting in a balance of 0.
Although the application does not actually set the token to USDT, it still fetches the balance, displaying 0 in the balance field of the swap form.

**To Reproduce**

1. First, switch your network to Base (USDT is unsupported on Base for now)
1. Go to the swap page with the URL containing an unsupported token (e.g., `localhost:3000?token=USDT&currency=NGN`).
2. Observe the balance field in the swap form.

**Expected behavior**

The application should not attempt to fetch the balance for unsupported tokens and should display an appropriate error message indicating the token is unsupported.

**Screenshots**

Image

**Environment:**

- OS: Windows 10
- Browser: Zen Browser
- Version: 1.10.1b

**Additional context**

1. The list of supported tokens should be dynamically fetched based on the current network.
2. The error message should be user-friendly and inform the user about the unsupported token.

### PR DESCRIPTION
**Pull request by sanjay-in**
### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.

This PR is to fix the unsupported token by the network provided in the URL the API fetches the rate of the unsupported tokens and no error message is provided

> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, contracts etc.

- Replaced the static tokens in `setDefaultValueOnPageLoad` with dynamically fetched supported tokens based on the network
- Created a boolean `useRef` named `isFirstRender` to prevent multiple display of error
- Added an user friendly toast error with title and description

### References

- Closes #101 

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this project has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.

- Entered manual token in URL like _USDT_ on _Base_ network and check for error and supported token value to fetch. 
- Check network tab if balance is being fetched
- Check for any unsupported token URL in any network

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [x] I have added documentation and tests for new/changed functionality in this PR
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not `main`

By submitting a PR, I agree to Paycrest's [Contributor Code of Conduct](https://paycrest.notion.site/Contributor-Code-of-Conduct-1602482d45a2806bab75fd314b381f4c) and [Contribution Guide](https://paycrest.notion.site/Contribution-Guide-1602482d45a2809a8930e6ad565c906a).

### CODE REVIEW

File: app/pages/TransactionForm.tsx [hunk 1]
```diff
@@ -185,6 +196,9 @@ export const TransactionForm = ({
       setIsReceiveInputActive(true);
     }
     // eslint-disable-next-line react-hooks/exhaustive-deps
+
+    // Setting first render to false
+    isFirsRender.current = false;
```
Comment (jeremy0x) [inline app/pages/TransactionForm.tsx:201]: move the `// eslint-disable-next-line react-hooks/exhaustive-deps` to be just before the dependency array

**Review by jeremy0x — CHANGES_REQUESTED** [review]
nice work, thanks for your contribution.

kindly address the requested changes

**Comment by sanjay-in** [comment]
Changes have been made. Thanks!

**Review by jeremy0x — DISMISSED** [review]

**Comment by jeremy0x** [comment]
will merge when the text update is made.

**Review by jeremy0x — APPROVED** [review]
everything LGTM
